name: Deploy to AWS EC2

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types: completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect to EC2 and Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: |
            docker pull saruprim/factorio:latest
            docker stop factorio || true
            docker rm factorio || true
            docker run -d --name factorio -p 34197:34197/udp -v factorio:/factorio --restart=unless-stopped saruprim/factorio

            eche "Check working..."
            sleep 10
            if [[ $(docker inspect --format={{.State.Status}} factorio) == "running" ]]; then
              echo "Server Factorio is OK"
            else
              echo "Server Factorio is NOK!!!"
              exit 1
            fi
     
